# Generated by Django 4.1.1 on 2022-09-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bug', 'BUG'), ('task', 'TASK'), ('story', 'STORY'), ('epic', 'EPIC')], max_length=7)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('reporter', models.CharField(max_length=50)),
                ('assignee', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'In Review'), (4, 'Code Complete'), (5, 'Done')], default=1, max_length=20)),
                ('anniversary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.project')),
            ],
        ),
    ]
