# Generated by Django 4.1.1 on 2022-09-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='anniversary',
            new_name='project_key',
        ),
    ]
