# Generated by Django 4.1.1 on 2022-09-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0002_rename_anniversary_issue_project_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project_key',
            new_name='project',
        ),
    ]
