# Generated by Django 4.1.1 on 2022-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0003_rename_project_key_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Code Complete', 'Code Complete'), ('Done', 'Done')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('BUG', 'BUG'), ('TASK', 'TASK'), ('STORY', 'STORY'), ('EPIC', 'EPIC')], max_length=7),
        ),
    ]
