# Generated by Django 4.1.1 on 2022-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0004_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Code Complete', 'Code Complete'), ('Done', 'Done')], default='Open', max_length=20),
        ),
    ]
