# Generated by Django 4.1.1 on 2022-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
            ],
        ),
    ]
